# Chinook 音乐项目配置
name: chinook
display_name: Chinook 音乐商店
description: 基于 Chinook 数据库的音乐商店管理系统
version: 1.0.0
author: LowCode Platform

# 数据库配置
database:
  type: sqlite
  path: chinook.db
  schema: schema.sql
  seed_data: data.sql

# 功能配置
features:
  multi_language: true      # 多语言支持
  custom_pages: true        # 自定义页面
  custom_views: false       # 自定义视图覆盖

# 依赖扩展
extensions: []

# UI 配置
ui:
  theme: default

# 项目元数据
metadata:
  created: 2026-02-19
  updated: 2026-02-19
  tags:
    - music
    - store
    - chinook
