<?php
	$data_fields_GenkinSuitochoEigyoKinshu = Array(
		"CreName" => "",
		"CreDate" => "",	
		"HJM_SYR_DTM" => "",
		"TEN_HJM_NO" => "",
		"TENPO_CD" => "",
		"TENPO_NM" => "",
		"MAISU_KOUKA" => "",
		"KINSYU_KOUKA" => "",
		"ZANDAKA_SHIHEI" => "",
		"MAISU_SHIHEI" => "",
		"KINSYU_SHIHEI" => "",
		"KINSYU_KOGITTE" => "",
		"ZANDAKA_KOGITTE" => "",
		"ZANDAKA_KOUKA" => "",
		"ZANDAKA_SHIHEI_SUM" => "",
		"ZANDAKA_KOUKA_SUM" => "",
		"ZANDAKA_KOGITTE_SUM" => "",
		"KON_HJM_EGK_KKS_GK" => "",
	
	);
?>