<?php
	$data_fields_rptShiharaiDenpyo = Array(
		"TORIHIKISAKI_CD" =>
"", "TORIHIKISAKI_NAME" => "", "PRINT_DATE" => "", "SYOHY_NO" => "", "KEIRI_DT"
=> "", "TEKYO" => "", "L_BUSYO_CD" => "", "L_BUSYO" => "", "R_BUSYO_CD" => "",
"L_KAMOKU_CD" => "", "L_KAMOKU" => "", "ZEIKM_GK" => "", "L_SYOHIZEI" => "",
"R_SYOHIZEI" => "", "R_KAMOKU_CD" => "","R_KAMOKU"=>"", "R_KAMOK_NM" => "",
"SHIHARAI_DT" => "","SHIHARAI" => "", "SHIKIN" => "", "R_BUSYO" => "",
"GINKOMEI" => "", "SHITEN_NM" => "", "SYUBETU" => "", "KOUZA_NO" => "",
"KOUZA_KN" => "", "UCHIWAKE1" => "", "L_SYOHIZEI_RT" => "", "R_SYOHIZEI_RT" =>
"", "CREATE_DATE" => "", "BIKOU" => "", "ZEIKM_GK_GOUKEI" => "","L_KAMCD" =>
"","L_KOUCD" => "","L_KAM_NAME" => "","L_SUBKAM_NAME" =>
"","R_KAMCD"=>"","R_KOUCD"=>"","R_KAMOKU"=>"","R_SUB_KAMOKU"=>"","SYAIN"=>"" ); ?>
