<?php
	$data = Array(
		"MEISYOU_CD" => "",
		"MEISYOU" => "",
		"DAISU" => "",
		"KAIYAKU" => "",
		"SYARYOU_PRC" => "",
		"SATEI" => "",
		"SAIMITUMORI" => "",
		"KASOU_URI" => "",
		"KASOU_PCS" => "",
		"SONOTA_URI" => "",
		"SONOTA" => "",
		"SITASON" => "",
		"RIEKI" => "",
		"TODAY" => "",
		"TOUGETU" => "",
	);
	$total = Array(
		"DAISU" => "0",
		"KAIYAKU" => "0",
		"SYARYOU_PRC" => "0",
		"SATEI" => "0",
		"SAIMITUMORI" => "0",
		"KASOU_URI" => "0",
		"KASOU_PCS" => "0",
		"SONOTA_URI" => "0",
		"SONOTA" => "0",
		"SITASON" => "0",
		"RIEKI" => "0"
	);
?>