<?php
	$data_fields_rptKijyunList = Array(
		"NENGETU" => "",
		"KBN" => "",
		"NAU_KB" => "",
		"UC_NO" => "",
		"CEL_DATE" => "",
		"BUSYO_CD" => "",
		"BUSYO_NM" => "",
		"SRY_PCS" => "",
		"KSO_PCS" => "",
		"KAP_TES_KYK" => "",
		"KAP_TES" => "",
		"SYH_KJN" => "",
		"UKM_KIN" => "",
		"CKO_SAI_MITUMORI" => "",
		"HNB_FUTANKIN" => "",
		"HMK_CD" => "",
		"KYK_HNS" => "",
		"URK_DAISU" => "",
		"URI_DAISU" => "",
		"GYO_DAISU" => "",
		"SIT_DAISU" => "",
		"TRK_KB" => "",
		"URI_GYOSYA" => "",
		"TODAY" => ""
	);
?>
