<?php
	$data = array(
		"BUHIN" =>
"", "BUHIN_SUM" => 0, "CAR_NO" => "", "GAICHU" => "", "GAICHU_SUM" => 0,
"GOUKEI" => "", "GOUKEI_SUM" => 0, "KANRYOBI" => "", "KBN" => "", "KBN_COUNT" =>
0, "KOUCHIN" => "", "KOUCHIN_SUM" => 0, "SYADAIKATA" => "", "TODAY" => "",
"TOUGETU" => "", "BUHIN_AVG" => 0, "GAICHU_AVG" => 0, "KOUCHIN_AVG" => 0,
"GOUKEI_AVG" => 0 ); $TOTALKBN = array( "BUHIN" => "", "BUHIN_SUM" => 0,
"CAR_NO" => "", "GAICHU" => "", "GAICHU_SUM" => 0, "GOUKEI" => "", "GOUKEI_SUM"
=> 0, "KANRYOBI" => "", "KBN" => "", "KBN_COUNT" => 0, "KOUCHIN" => "",
"KOUCHIN_SUM" => 0, "SYADAIKATA" => "", "TODAY" => "", "TOUGETU" => "",
"BUHIN_AVG" => 0, "GAICHU_AVG" => 0, "KOUCHIN_AVG" => 0, "GOUKEI_AVG" => 0 );
$TOTALKBN1 = array( "BUHIN" => "", "BUHIN_SUM" => 0, "CAR_NO" => "", "GAICHU" =>
"", "GAICHU_SUM" => 0, "GOUKEI" => "", "GOUKEI_SUM" => 0, "KANRYOBI" => "",
"KBN" => "", "KBN_COUNT" => 0, "KOUCHIN" => "", "KOUCHIN_SUM" => 0, "SYADAIKATA"
=> "", "TODAY" => "", "TOUGETU" => "", "BUHIN_AVG" => 0, "GAICHU_AVG" => 0,
"KOUCHIN_AVG" => 0, "GOUKEI_AVG" => 0 ); $TOTAL = array( "BUHIN" => "",
"BUHIN_SUM" => 0, "CAR_NO" => "", "GAICHU" => "", "GAICHU_SUM" => 0, "GOUKEI" =>
"", "GOUKEI_SUM" => 0, "KANRYOBI" => "", "KBN" => "", "KBN_COUNT" => 0,
"KOUCHIN" => "", "KOUCHIN_SUM" => 0, "SYADAIKATA" => "", "TODAY" => "",
"TOUGETU" => "", "BUHIN_AVG" => 0, "GAICHU_AVG" => 0, "KOUCHIN_AVG" => 0,
"GOUKEI_AVG" => 0 ); ?>
