<?php
	$data_fields_rptSiwakeErrList = Array(
		"NEN" => "",
		"TUKI" => "",
		"TODAY" => "",
		"TITLE" => "",
		"KEIJO_DT" => "",
		"DENPY_NO" => "",
		"TAISK_KB" => "",
		"BUSYO_CD" => "",
		"KAMOK_CD" => "",
		"HIMOK_CD" => "",
		"TAISK_KB" => "", //---20151027 li ADD.
		"KEIJO_GK" => "",
		"AITE_BUSYO_CD" => "",
		"AITE_KAMOK_CD" => "",
		"AITE_HIMOK_CD" => "",
		"HASEI_MOTO_KB" => "",
		"KAMOK_NM" => "",
		"BUSYO_NM" => "",
		"ERR" => ""
	);
?>
