<?php
	$data_fields_rptZandakaList = Array(
		"NEN" => "2014",
		"TUKI" => "09",
		"TODAY" => "2014/09/25",
		"TITLE" => "整備売掛金　残高／金利　データ",
		"ZEN_ZAN" => "123456789",
		"TOU_GK" => "123456798",
		"TAISYOU_GK" => "123456789",
		"BUSYO_CD" => "699",
		"KAMOK_CD" => "01236",
		"ZEN_GK" => "123456",
		"KINRI_GK" => "123456789",
		"NISSU" => "12345789",
		"KBN" => "a1",
		"KAMOK_NM" => "大連のテストデータ",
		"BUSYO_NM" => "付テストデータ",
		"NISSU"=> "1234"
	);
?>
