<?php
	$data_fields_rptDenpyoinsatu = Array(
		"SYOHY_NO" => "",
		"PRINT_DATE" => "",
		"L_KAMOKU" => "",
		"R_KAMOKU" => "",
		"L_BUSYO" => "",
		"R_BUSYO" => "",
		"ZEIKM_GK" => "",
		"L_SYOHIZEI" => "",
		"R_SYOHIZEI" => "",
		"TEKYO" => "",
		"KEIRI_DT" => "",
		"BIKOU" => "",
		"L_BUSYO_CD" => "",
		"R_BUSYO_CD" => "",
		"L_KAMOKU_CD" => "",
		"R_KAMOKU_CD" => "",
		"ZEIKM_GK_GOUKEI" => "",
	);
?>