<?php
	$data = Array(
		"KRI_DATE" => "",
		"URI_GYOSYA" => "",
		"GYO_NAME" => "",
		"URI_BUSYO_CD" => "",
		"UC_NO" => "",
		"MGN_NIN" => "",
		"CMN_NO" => "",
		"HNB_TES_GKU" => "",
		"HNB_SHZ" => "",
		"HNB_TESURYO" => "",
		"SYAIN_NO" => "",
		"WHERE_KRI_DATE" => "",
		"KEIJYO_YM" => "",
		"BUSYO_CD" => ""
	);
	$total = array(
		"HNB_TES_GKU" => "0",
		"HNB_SHZ" => "0",
		"HNB_TESURYO" => "0"
	);
	$total1 = array(
		"HNB_TES_GKU" => "0",
		"HNB_SHZ" => "0",
		"HNB_TESURYO" => "0"
	);
?>