<?php
	$data = Array(
		"CNT" => "",
		"TOURK_NO1" => "",
		"TOURK_NO23" => "",
		"SYADAI" => "",
		"CARNO" => "",
		"TOU_DATE" => "",
		"SYARYO_DAI" => "",
		"SYARYO_SHZ" => "",
		"SYARYO_SHZ_RT" => "",
		"TOUROKURYO" => "",
		"SYARYOU_ZEI" => "",
		"RCYL_GK" => "",
		"JYURYO_ZEI" => "",
		"JIDOUSYA_ZEI" => "",
		"JIBAI_HOK_RYO" => "",
		"KASOUHI" => "",
		"KASOUZEI" => "",
		"SITADORI" => "",
		"MGN_MEI_KNJ1" => "",
		"SYOUKEI" => "",
		"TODAY" => "",
		"TOUGETU" => "",
		"KINGAKU" => "",
		"SYOUHIZEI" => "",
		"CMN_NO" => "",
		"SYAIN_NM" => ""
	);
	$total = Array(
		"SYOUKEI" => "0",
		"SYARYO_DAI" => "0",
		"SYARYO_SHZ" => "0",
		"TOUROKURYO" => "0",
		"SYARYOU_ZEI" => "0",
		"RCYL_GK" => "0",
		"JYURYO_ZEI" => "0",
		"JIDOUSYA_ZEI" => "0",
		"JIBAI_HOK_RYO" => "0",
		"KASOUHI" => "0",
		"KASOUZEI" => "0",
		"SITADORI" => "0"
	);
	$total1 = Array(
		"SYOUKEI" => "0",
		"SYARYO_DAI" => "0",
		"SYARYO_SHZ" => "0",
		"TOUROKURYO" => "0",
		"SYARYOU_ZEI" => "0",
		"RCYL_GK" => "0",
		"JYURYO_ZEI" => "0",
		"JIDOUSYA_ZEI" => "0",
		"JIBAI_HOK_RYO" => "0",
		"KASOUHI" => "0",
		"KASOUZEI" => "0",
		"SITADORI" => "0"
	);
?>