<?php
	$Detail = array(
		'GYOUSYA_NM' => 'A',
		'SYADAIKATA' => 'B',
		'MEIGININ' => 'C',
		'KAIYAKU_KB' => 'D',
		'SIN_URIAGE' => 'E',
		'CHU_URIAGE' => 'E',
		'TA_URIAGE' => 'E',
		'SIN_SYARYOU_RIEKI' => 'F',
		'CHU_SYARYOU_RIEKI' => 'F',
		'TA_SYARYOU_RIEKI' => 'F',
		'SIN_KASOU_RIEKI' => 'G',
		'CHU_KASOU_RIEKI' => 'G',
		'TA_KASOU_RIEKI' => 'G',
		'SIN_KAPPU_RIEKI' => 'H',
		'CHU_KAPPU_RIEKI' => 'H',
		'TA_KAPPU_RIEKI' => 'H',
		'SIN_TOUROKU_RIEKI' => 'I',
		'CHU_TOUROKU_RIEKI' => 'I',
		'TA_TOUROKU_RIEKI' => 'I',
		'SIN_UCHIKOMIKIN' => 'J',
		'CHU_UCHIKOMIKIN' => 'J',
		'TA_UCHIKOMIKIN' => 'J',
		'SIN_URI_GENKA' => 'K',
		'CHU_URI_GENKA' => 'K',
		'TA_URI_GENKA' => 'K',
		'SIN_SITADORI_SON' => 'L',
		'CHU_SITADORI_SON' => 'L',
		'TA_SITADORI_SON' => 'L',
		'SIN_HANBAITESURYO' => 'M',
		'CHU_HANBAITESURYO' => 'M',
		'TA_HANBAITESURYO' => 'M',
		'SIN_SYOUKAIRYO' => 'N',
		'CHU_SYOUKAIRYO' => 'N',
		'TA_SYOUKAIRYO' => 'N',
		'SIN_CHUKOSYA_GENRI' => 'O',
		'CHU_CHUKOSYA_GENRI' => 'O',
		'TA_CHUKOSYA_GENRI' => 'O',
		'SIN_TOUGETU_GENRI' => 'P',
		'CHU_TOUGETU_GENRI' => 'P',
		'TA_TOUGETU_GENRI' => 'P',
		'UC_NO' => 'Q',
		'CMN_NO' => 'R'
	);
	$SIN_Tatol_Excel = array(
		'SIN_URIAGE' => 'E',
		'SIN_SYARYOU_RIEKI' => 'F',
		'SIN_KASOU_RIEKI' => 'G',
		'SIN_KAPPU_RIEKI' => 'H',
		'SIN_TOUROKU_RIEKI' => 'I',
		'SIN_UCHIKOMIKIN' => 'J',
		'SIN_URI_GENKA' => 'K',
		'SIN_SITADORI_SON' => 'L',
		'SIN_HANBAITESURYO' => 'M',
		'SIN_SYOUKAIRYO' => 'N',
		'SIN_CHUKOSYA_GENRI' => 'O',
		'SIN_TOUGETU_GENRI' => 'P',
		'SIN_TOUKI_GENKAIRIEKI' => 'Q'
	);
	$SIN_AVG_Excel = array(
		'SIN_URIAGE_AVG' => 'E',
		'SIN_SYARYOU_RIEKI_AVG' => 'F',
		'SIN_KASOU_RIEKI_AVG' => 'G',
		'SIN_KAPPU_RIEKI_AVG' => 'H',
		'SIN_TOUROKU_RIEKI_AVG' => 'I',
		'SIN_UCHIKOMIKIN_AVG' => 'J',
		'SIN_URI_GENKA_AVG' => 'K',
		'SIN_SITADORI_SON_AVG' => 'L',
		'SIN_HANBAITESURYO_AVG' => 'M',
		'SIN_SYOUKAIRYO_AVG' => 'N',
		'SIN_CHUKOSYA_GENRI_AVG' => 'O',
		'SIN_TOUGETU_GENRI_AVG' => 'P',
		'SIN_TOUKI_GENKAIRIEKI_AVG' => 'Q'
	);
	$CHU_Tatol_Excel = array(
		'CHU_URIAGE' => 'E',
		'CHU_SYARYOU_RIEKI' => 'F',
		'CHU_KASOU_RIEKI' => 'G',
		'CHU_KAPPU_RIEKI' => 'H',
		'CHU_TOUROKU_RIEKI' => 'I',
		'CHU_UCHIKOMIKIN' => 'J',
		'CHU_URI_GENKA' => 'K',
		'CHU_SITADORI_SON' => 'L',
		'CHU_HANBAITESURYO' => 'M',
		'CHU_SYOUKAIRYO' => 'N',
		'CHU_CHUKOSYA_GENRI' => 'O',
		'CHU_TOUGETU_GENRI' => 'P',
		'CHU_TOUKI_GENKAIRIEKI' => 'Q'
	);
	$CHU_AVG_Excel = array(
		'CHU_URIAGE_AVG' => 'E',
		'CHU_SYARYOU_RIEKI_AVG' => 'F',
		'CHU_KASOU_RIEKI_AVG' => 'G',
		'CHU_KAPPU_RIEKI_AVG' => 'H',
		'CHU_TOUROKU_RIEKI_AVG' => 'I',
		'CHU_UCHIKOMIKIN_AVG' => 'J',
		'CHU_URI_GENKA_AVG' => 'K',
		'CHU_SITADORI_SON_AVG' => 'L',
		'CHU_HANBAITESURYO_AVG' => 'M',
		'CHU_SYOUKAIRYO_AVG' => 'N',
		'CHU_CHUKOSYA_GENRI_AVG' => 'O',
		'CHU_TOUGETU_GENRI_AVG' => 'P',
		'CHU_TOUKI_GENKAIRIEKI_AVG' => 'Q'
	);
	$TA_Tatol_Excel = array(
		'TA_URIAGE' => 'E',
		'TA_SYARYOU_RIEKI' => 'F',
		'TA_KASOU_RIEKI' => 'G',
		'TA_KAPPU_RIEKI' => 'H',
		'TA_TOUROKU_RIEKI' => 'I',
		'TA_UCHIKOMIKIN' => 'J',
		'TA_URI_GENKA' => 'K',
		'TA_SITADORI_SON' => 'L',
		'TA_HANBAITESURYO' => 'M',
		'TA_SYOUKAIRYO' => 'N',
		'TA_CHUKOSYA_GENRI' => 'O',
		'TA_TOUGETU_GENRI' => 'P',
		'TA_TOUKI_GENKAIRIEKI' => 'Q'
	);
	$TA_AVG_Excel = array(
		'TA_URIAGE_AVG' => 'E',
		'TA_SYARYOU_RIEKI_AVG' => 'F',
		'TA_KASOU_RIEKI_AVG' => 'G',
		'TA_KAPPU_RIEKI_AVG' => 'H',
		'TA_TOUROKU_RIEKI_AVG' => 'I',
		'TA_UCHIKOMIKIN_AVG' => 'J',
		'TA_URI_GENKA_AVG' => 'K',
		'TA_SITADORI_SON_AVG' => 'L',
		'TA_HANBAITESURYO_AVG' => 'M',
		'TA_SYOUKAIRYO_AVG' => 'N',
		'TA_CHUKOSYA_GENRI_AVG' => 'O',
		'TA_TOUGETU_GENRI_AVG' => 'P',
		'TA_TOUKI_GENKAIRIEKI_AVG' => 'Q'
	);
	
	$SIN_SYAIN = array(
		'TODAY' => "",
		'ATUKAI_BUSYO' => "",
		'BUSYO_NM' => "",
		'ATUKAI_SYAIN' => "",
		'SYAINMEI' => "",
		'SIN_TOUKI_DAISU' => 0,
		//売上
		'SIN_DAISU' => 0,
		//下取
		'SIN_SIT_DAISU' => 0,

		'SIN_URIAGE' => 0,
		'SIN_SYARYOU_RIEKI' => 0,
		'SIN_KASOU_RIEKI' => 0,
		'SIN_KAPPU_RIEKI' => 0,
		'SIN_TOUROKU_RIEKI' => 0,
		'SIN_UCHIKOMIKIN' => 0,
		'SIN_URI_GENKA' => 0,
		'SIN_SITADORI_SON' => 0,
		'SIN_HANBAITESURYO' => 0,
		'SIN_SYOUKAIRYO' => 0,
		'SIN_CHUKOSYA_GENRI' => 0,
		'SIN_TOUGETU_GENRI' => 0,
		'SIN_TOUKI_GENKAIRIEKI' => 0,
		'SIN_TOUKI_DAISU_BUSYO' => 0,
		'SIN_TOUKI_GENKAIRIEKI_BUSYO' => 0
	);
	$SIN_SYAIN1 = array(
		'TODAY' => "",
		'ATUKAI_BUSYO' => "",
		'BUSYO_NM' => "",
		'ATUKAI_SYAIN' => "",
		'SYAINMEI' => "",
		'SIN_TOUKI_DAISU' => 0,
		//売上
		'SIN_DAISU' => 0,
		//下取
		'SIN_SIT_DAISU' => 0,

		'SIN_URIAGE' => 0,
		'SIN_SYARYOU_RIEKI' => 0,
		'SIN_KASOU_RIEKI' => 0,
		'SIN_KAPPU_RIEKI' => 0,
		'SIN_TOUROKU_RIEKI' => 0,
		'SIN_UCHIKOMIKIN' => 0,
		'SIN_URI_GENKA' => 0,
		'SIN_SITADORI_SON' => 0,
		'SIN_HANBAITESURYO' => 0,
		'SIN_SYOUKAIRYO' => 0,
		'SIN_CHUKOSYA_GENRI' => 0,
		'SIN_TOUGETU_GENRI' => 0,
		'SIN_TOUKI_GENKAIRIEKI' => 0,
		'SIN_TOUKI_DAISU_BUSYO' => 0,
		'SIN_TOUKI_GENKAIRIEKI_BUSYO' => 0
	);
	$CHU_SYAIN = array(
		'TODAY' => "",
		'ATUKAI_BUSYO' => "",
		'BUSYO_NM' => "",
		'ATUKAI_SYAIN' => "",
		'SYAINMEI' => "",
		'CHU_TOUKI_DAISU' => 0,
		//売上
		'CHU_DAISU' => 0,
		//下取
		'CHU_SIT_DAISU' => 0,

		'CHU_URIAGE' => 0,
		'CHU_SYARYOU_RIEKI' => 0,
		'CHU_KASOU_RIEKI' => 0,
		'CHU_KAPPU_RIEKI' => 0,
		'CHU_TOUROKU_RIEKI' => 0,
		'CHU_UCHIKOMIKIN' => 0,
		'CHU_URI_GENKA' => 0,
		'CHU_SITADORI_SON' => 0,
		'CHU_HANBAITESURYO' => 0,
		'CHU_SYOUKAIRYO' => 0,
		'CHU_CHUKOSYA_GENRI' => 0,
		'CHU_TOUGETU_GENRI' => 0,
		'CHU_TOUKI_GENKAIRIEKI' => 0,
		'CHU_TOUKI_DAISU_BUSYO' => 0,
		'CHU_TOUKI_GENKAIRIEKI_BUSYO' => 0
	);
	$CHU_SYAIN1 = array(
		'TODAY' => "",
		'ATUKAI_BUSYO' => "",
		'BUSYO_NM' => "",
		'ATUKAI_SYAIN' => "",
		'SYAINMEI' => "",
		'CHU_TOUKI_DAISU' => 0,
		//売上
		'CHU_DAISU' => 0,
		//下取
		'CHU_SIT_DAISU' => 0,

		'CHU_URIAGE' => 0,
		'CHU_SYARYOU_RIEKI' => 0,
		'CHU_KASOU_RIEKI' => 0,
		'CHU_KAPPU_RIEKI' => 0,
		'CHU_TOUROKU_RIEKI' => 0,
		'CHU_UCHIKOMIKIN' => 0,
		'CHU_URI_GENKA' => 0,
		'CHU_SITADORI_SON' => 0,
		'CHU_HANBAITESURYO' => 0,
		'CHU_SYOUKAIRYO' => 0,
		'CHU_CHUKOSYA_GENRI' => 0,
		'CHU_TOUGETU_GENRI' => 0,
		'CHU_TOUKI_GENKAIRIEKI' => 0,
		'CHU_TOUKI_DAISU_BUSYO' => 0,
		'CHU_TOUKI_GENKAIRIEKI_BUSYO' => 0
	);
	$TA_SYAIN = array(
		'TODAY' => "",
		'ATUKAI_BUSYO' => "",
		'BUSYO_NM' => "",
		'ATUKAI_SYAIN' => "",
		'SYAINMEI' => "",
		'TA_TOUKI_DAISU' => 0,
		//売上
		'TA_DAISU' => 0,
		//下取
		'TA_SIT_DAISU' => 0,

		'TA_URIAGE' => 0,
		'TA_SYARYOU_RIEKI' => 0,
		'TA_KASOU_RIEKI' => 0,
		'TA_KAPPU_RIEKI' => 0,
		'TA_TOUROKU_RIEKI' => 0,
		'TA_UCHIKOMIKIN' => 0,
		'TA_URI_GENKA' => 0,
		'TA_SITADORI_SON' => 0,
		'TA_HANBAITESURYO' => 0,
		'TA_SYOUKAIRYO' => 0,
		'TA_CHUKOSYA_GENRI' => 0,
		'TA_TOUGETU_GENRI' => 0,
		'TA_TOUKI_GENKAIRIEKI' => 0,
		'TA_TOUKI_DAISU_BUSYO' => 0,
		'TA_TOUKI_GENKAIRIEKI_BUSYO' => 0
	);
	$TA_SYAIN1 = array(
		'TODAY' => "",
		'ATUKAI_BUSYO' => "",
		'BUSYO_NM' => "",
		'ATUKAI_SYAIN' => "",
		'SYAINMEI' => "",
		'TA_TOUKI_DAISU' => 0,
		//売上
		'TA_DAISU' => 0,
		//下取
		'TA_SIT_DAISU' => 0,

		'TA_URIAGE' => 0,
		'TA_SYARYOU_RIEKI' => 0,
		'TA_KASOU_RIEKI' => 0,
		'TA_KAPPU_RIEKI' => 0,
		'TA_TOUROKU_RIEKI' => 0,
		'TA_UCHIKOMIKIN' => 0,
		'TA_URI_GENKA' => 0,
		'TA_SITADORI_SON' => 0,
		'TA_HANBAITESURYO' => 0,
		'TA_SYOUKAIRYO' => 0,
		'TA_CHUKOSYA_GENRI' => 0,
		'TA_TOUGETU_GENRI' => 0,
		'TA_TOUKI_GENKAIRIEKI' => 0,
		'TA_TOUKI_DAISU_BUSYO' => 0,
		'TA_TOUKI_GENKAIRIEKI_BUSYO' => 0
	);
	$SIN_BUSYO = array(
		'TODAY' => "",
		'ATUKAI_BUSYO' => "",
		'BUSYO_NM' => "",
		'ATUKAI_SYAIN' => "",
		'SYAINMEI' => "",
		'SIN_TOUKI_DAISU' => 0,
		//売上
		'SIN_DAISU' => 0,
		//下取
		'SIN_SIT_DAISU' => 0,

		'SIN_URIAGE' => 0,
		'SIN_SYARYOU_RIEKI' => 0,
		'SIN_KASOU_RIEKI' => 0,
		'SIN_KAPPU_RIEKI' => 0,
		'SIN_TOUROKU_RIEKI' => 0,
		'SIN_UCHIKOMIKIN' => 0,
		'SIN_URI_GENKA' => 0,
		'SIN_SITADORI_SON' => 0,
		'SIN_HANBAITESURYO' => 0,
		'SIN_SYOUKAIRYO' => 0,
		'SIN_CHUKOSYA_GENRI' => 0,
		'SIN_TOUGETU_GENRI' => 0,
		'SIN_TOUKI_GENKAIRIEKI' => 0,
		'SIN_TOUKI_DAISU_BUSYO' => 0,
		'SIN_TOUKI_GENKAIRIEKI_BUSYO' => 0
	);
	$SIN_BUSYO1 = array(
		'TODAY' => "",
		'ATUKAI_BUSYO' => "",
		'BUSYO_NM' => "",
		'ATUKAI_SYAIN' => "",
		'SYAINMEI' => "",
		'SIN_TOUKI_DAISU' => 0,
		//売上
		'SIN_DAISU' => 0,
		//下取
		'SIN_SIT_DAISU' => 0,

		'SIN_URIAGE' => 0,
		'SIN_SYARYOU_RIEKI' => 0,
		'SIN_KASOU_RIEKI' => 0,
		'SIN_KAPPU_RIEKI' => 0,
		'SIN_TOUROKU_RIEKI' => 0,
		'SIN_UCHIKOMIKIN' => 0,
		'SIN_URI_GENKA' => 0,
		'SIN_SITADORI_SON' => 0,
		'SIN_HANBAITESURYO' => 0,
		'SIN_SYOUKAIRYO' => 0,
		'SIN_CHUKOSYA_GENRI' => 0,
		'SIN_TOUGETU_GENRI' => 0,
		'SIN_TOUKI_GENKAIRIEKI' => 0,
		'SIN_TOUKI_DAISU_BUSYO' => 0,
		'SIN_TOUKI_GENKAIRIEKI_BUSYO' => 0
	);
	$CHU_BUSYO = array(
		'TODAY' => "",
		'ATUKAI_BUSYO' => "",
		'BUSYO_NM' => "",
		'ATUKAI_SYAIN' => "",
		'SYAINMEI' => "",
		'CHU_TOUKI_DAISU' => 0,
		//売上
		'CHU_DAISU' => 0,
		//下取
		'CHU_SIT_DAISU' => 0,

		'CHU_URIAGE' => 0,
		'CHU_SYARYOU_RIEKI' => 0,
		'CHU_KASOU_RIEKI' => 0,
		'CHU_KAPPU_RIEKI' => 0,
		'CHU_TOUROKU_RIEKI' => 0,
		'CHU_UCHIKOMIKIN' => 0,
		'CHU_URI_GENKA' => 0,
		'CHU_SITADORI_SON' => 0,
		'CHU_HANBAITESURYO' => 0,
		'CHU_SYOUKAIRYO' => 0,
		'CHU_CHUKOSYA_GENRI' => 0,
		'CHU_TOUGETU_GENRI' => 0,
		'CHU_TOUKI_GENKAIRIEKI' => 0,
		'CHU_TOUKI_DAISU_BUSYO' => 0,
		'CHU_TOUKI_GENKAIRIEKI_BUSYO' => 0
	);
	$CHU_BUSYO1 = array(
		'TODAY' => "",
		'ATUKAI_BUSYO' => "",
		'BUSYO_NM' => "",
		'ATUKAI_SYAIN' => "",
		'SYAINMEI' => "",
		'CHU_TOUKI_DAISU' => 0,
		//売上
		'CHU_DAISU' => 0,
		//下取
		'CHU_SIT_DAISU' => 0,

		'CHU_URIAGE' => 0,
		'CHU_SYARYOU_RIEKI' => 0,
		'CHU_KASOU_RIEKI' => 0,
		'CHU_KAPPU_RIEKI' => 0,
		'CHU_TOUROKU_RIEKI' => 0,
		'CHU_UCHIKOMIKIN' => 0,
		'CHU_URI_GENKA' => 0,
		'CHU_SITADORI_SON' => 0,
		'CHU_HANBAITESURYO' => 0,
		'CHU_SYOUKAIRYO' => 0,
		'CHU_CHUKOSYA_GENRI' => 0,
		'CHU_TOUGETU_GENRI' => 0,
		'CHU_TOUKI_GENKAIRIEKI' => 0,
		'CHU_TOUKI_DAISU_BUSYO' => 0,
		'CHU_TOUKI_GENKAIRIEKI_BUSYO' => 0
	);
	$TA_BUSYO = array(
		'TODAY' => "",
		'ATUKAI_BUSYO' => "",
		'BUSYO_NM' => "",
		'ATUKAI_SYAIN' => "",
		'SYAINMEI' => "",
		'TA_TOUKI_DAISU' => 0,
		//売上
		'TA_DAISU' => 0,
		//下取
		'TA_SIT_DAISU' => 0,

		'TA_URIAGE' => 0,
		'TA_SYARYOU_RIEKI' => 0,
		'TA_KASOU_RIEKI' => 0,
		'TA_KAPPU_RIEKI' => 0,
		'TA_TOUROKU_RIEKI' => 0,
		'TA_UCHIKOMIKIN' => 0,
		'TA_URI_GENKA' => 0,
		'TA_SITADORI_SON' => 0,
		'TA_HANBAITESURYO' => 0,
		'TA_SYOUKAIRYO' => 0,
		'TA_CHUKOSYA_GENRI' => 0,
		'TA_TOUGETU_GENRI' => 0,
		'TA_TOUKI_GENKAIRIEKI' => 0,
		'TA_TOUKI_DAISU_BUSYO' => 0,
		'TA_TOUKI_GENKAIRIEKI_BUSYO' => 0
	);
	$TA_BUSYO1 = array(
		'TODAY' => "",
		'ATUKAI_BUSYO' => "",
		'BUSYO_NM' => "",
		'ATUKAI_SYAIN' => "",
		'SYAINMEI' => "",
		'TA_TOUKI_DAISU' => 0,
		//売上
		'TA_DAISU' => 0,
		//下取
		'TA_SIT_DAISU' => 0,

		'TA_URIAGE' => 0,
		'TA_SYARYOU_RIEKI' => 0,
		'TA_KASOU_RIEKI' => 0,
		'TA_KAPPU_RIEKI' => 0,
		'TA_TOUROKU_RIEKI' => 0,
		'TA_UCHIKOMIKIN' => 0,
		'TA_URI_GENKA' => 0,
		'TA_SITADORI_SON' => 0,
		'TA_HANBAITESURYO' => 0,
		'TA_SYOUKAIRYO' => 0,
		'TA_CHUKOSYA_GENRI' => 0,
		'TA_TOUGETU_GENRI' => 0,
		'TA_TOUKI_GENKAIRIEKI' => 0,
		'TA_TOUKI_DAISU_BUSYO' => 0,
		'TA_TOUKI_GENKAIRIEKI_BUSYO' => 0
	);
	$SIN_TOTAL = array(
		'TODAY' => "",
		'SIN_TOUKI_DAISU_TOTAL' => '',
		//売上
		'SIN_DAISU' => 0,
		//下取
		'SIN_SIT_DAISU' => 0,

		'SIN_URIAGE' => 0,
		'SIN_SYARYOU_RIEKI' => 0,
		'SIN_KASOU_RIEKI' => 0,
		'SIN_KAPPU_RIEKI' => 0,
		'SIN_TOUROKU_RIEKI' => 0,
		'SIN_UCHIKOMIKIN' => 0,
		'SIN_URI_GENKA' => 0,
		'SIN_SITADORI_SON' => 0,
		'SIN_HANBAITESURYO' => 0,
		'SIN_SYOUKAIRYO' => 0,
		'SIN_CHUKOSYA_GENRI' => 0,
		'SIN_TOUGETU_GENRI' => 0,
		'SIN_TOUKI_GENKAIRIEKI' => 0,
		'SIN_TOUKI_GENKAIRIEKI_TOTAL'=>''
	);
	$CHU_TOTAL = array(
		'TODAY' => "",
		'CHU_TOUKI_DAISU_TOTAL' => '',
		//中古車
		'CHU_DAISU' => 0,
		//下取
		'CHU_SIT_DAISU' => 0,

		'CHU_URIAGE' => 0,
		'CHU_SYARYOU_RIEKI' => 0,
		'CHU_KASOU_RIEKI' => 0,
		'CHU_KAPPU_RIEKI' => 0,
		'CHU_TOUROKU_RIEKI' => 0,
		'CHU_UCHIKOMIKIN' => 0,
		'CHU_URI_GENKA' => 0,
		'CHU_SITADORI_SON' => 0,
		'CHU_HANBAITESURYO' => 0,
		'CHU_SYOUKAIRYO' => 0,
		'CHU_CHUKOSYA_GENRI' => 0,
		'CHU_TOUGETU_GENRI' => 0,
		'CHU_TOUKI_GENKAIRIEKI' => 0,
		'CHU_TOUKI_GENKAIRIEKI_TOTAL'=>''
	);
	$TA_TOTAL = array(
		'TODAY' => "",
		'TA_TOUKI_DAISU_TOTAL' => '',
		//他ﾁｬﾝﾈﾙ
		'TA_DAISU' => 0,
		//下取
		'TA_SIT_DAISU' => 0,

		'TA_URIAGE' => 0,
		'TA_SYARYOU_RIEKI' => 0,
		'TA_KASOU_RIEKI' => 0,
		'TA_KAPPU_RIEKI' => 0,
		'TA_TOUROKU_RIEKI' => 0,
		'TA_UCHIKOMIKIN' => 0,
		'TA_URI_GENKA' => 0,
		'TA_SITADORI_SON' => 0,
		'TA_HANBAITESURYO' => 0,
		'TA_SYOUKAIRYO' => 0,
		'TA_CHUKOSYA_GENRI' => 0,
		'TA_TOUGETU_GENRI' => 0,
		'TA_TOUKI_GENKAIRIEKI' => 0,
		'TA_TOUKI_GENKAIRIEKI_TOTAL'=>''
	);
    $checklist = array(
        'ATUKAI_BUSYO'=>'A',
        'BUSYO_NM'=>'B',
        'SYAINMEI' => 'C',
        'SYADAIKATA' => 'D',
        'MEIGININ' => 'E',
        'KAIYAKU_KB' => 'F',
        'SIN_URIAGE' => 'G',
        'CHU_URIAGE' => 'G',
        'TA_URIAGE' => 'G',
        'SIN_SYARYOU_RIEKI' => 'H',
        'CHU_SYARYOU_RIEKI' => 'H',
        'TA_SYARYOU_RIEKI' => 'H',
        'SIN_KASOU_RIEKI' => 'I',
        'CHU_KASOU_RIEKI' => 'I',
        'TA_KASOU_RIEKI' => 'I',
        'SIN_KAPPU_RIEKI' => 'J',
        'CHU_KAPPU_RIEKI' => 'J',
        'TA_KAPPU_RIEKI' => 'J',
        'SIN_TOUROKU_RIEKI' => 'K',
        'CHU_TOUROKU_RIEKI' => 'K',
        'TA_TOUROKU_RIEKI' => 'K',
        'SIN_UCHIKOMIKIN' => 'L',
        'CHU_UCHIKOMIKIN' => 'L',
        'TA_UCHIKOMIKIN' => 'L',
        'SIN_URI_GENKA' => 'M',
        'CHU_URI_GENKA' => 'M',
        'TA_URI_GENKA' => 'M',
        'SIN_SITADORI_SON' => 'N',
        'CHU_SITADORI_SON' => 'N',
        'TA_SITADORI_SON' => 'N',
        'SIN_HANBAITESURYO' => 'O',
        'CHU_HANBAITESURYO' => 'O',
        'TA_HANBAITESURYO' => 'O',
        'SIN_SYOUKAIRYO' => 'P',
        'CHU_SYOUKAIRYO' => 'P',
        'TA_SYOUKAIRYO' => 'P',
        'SIN_CHUKOSYA_GENRI' => 'Q',
        'CHU_CHUKOSYA_GENRI' => 'Q',
        'TA_CHUKOSYA_GENRI' => 'Q',
        'SIN_TOUGETU_GENRI' => 'R',
        'CHU_TOUGETU_GENRI' => 'R',
        'TA_TOUGETU_GENRI' => 'R',
        'UC_NO' => 'S',
        'CMN_NO' => 'T',
    );
    
?>